---

image: "quay.io/luzifer/repo-runner-image"
checkout_dir: /go/src/github.com/Luzifer/dirsize

commands:
  - make publish

environment:
  ARCHS: darwin/386 darwin/amd64 linux/386 linux/amd64 linux/arm freebsd/386 freebsd/amd64 openbsd/386 openbsd/amd64 windows/386 windows/amd64 freebsd/arm netbsd/386 netbsd/amd64 netbsd/arm
  CGO_ENABLED: 0
